# ~/cerebtests/cerebunit/validation_tests/cells/PurkinjeCell/__init__.py
from .test_for_soma_restVm import SomaRestingVmTest
from .test_for_soma_spikeheight_with_antidromic_stimulation import SomaSpikeHeightAntidromicTest
